////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#print_engine_runtime]
= Print Engine Runtime
This section covers the API for the _Print Engine Runtime_, a package that provides the core implementation behind the interfaces of the <<print_engine_api, Print Engine API>>.

[#print_job_manager]
== PrintJobManager

The `PrintJobManager` is an implementation of the <<job_manager, JobManager>>, that facilitates the creation of <<print_job, PrintJob>>s and the preparation of Print Models.

[source,java,title="PrintJobManager implementation"]
----
include::../../sourceCode/engine-runtime/main/java/com/mgmtp/a12/print/engine/runtime/PrintJobManager.java[tag=PrintJobManager]
}
----

[#print_job_manager_api]
== PrintJobManagerApi

The `PrintJobManagerApi` provides interfaces for the loading of Print Models and Document Models by given their IDs.

[source,java,title="PrintJobManagerApi interface"]
----
include::../../sourceCode/engine-runtime/main/java/com/mgmtp/a12/print/engine/runtime/PrintJobManager.java[tag=PrintJobManagerApi,indent=0]
----

[#pdf_box_print_engine_runtime]
== PdfBoxPrintEngine

The `PdfBoxPrintEngine` is an implementation of <<pdf_box_print_engine, PdfBoxPrintEngine>>, that provides the ability to execute <<print_job, PrintJob>>s.
This engine is able to work with Typesetting Models, which can be provided with the <<typesetting_model_provider, TypesettingModelProvider>>.

[#pdf_print_engine_runtime]
== PdfPrintEngine (Deprecated)

CAUTION: Will be replaced with <<pdf_box_print_engine_runtime, PdfBoxPrintEngine>> in 2026.06.

The `PdfPrintEngine` is an implementation of <<pdf_print_engine, PdfPrintEngine>>, that provides the ability to execute <<print_job, PrintJob>>s.
There are noticable differences to the `PdfBoxPrintEngine` (see link:/docs/PRINT_ENGINE/print-modeling-documentation/index.html#legacy_rendering_mode[Legacy Rendering Mode]).

[#kernel_document_v2_provider]
== KernelDocumentV2Provider

`KernelDocumentV2Provider` is an interface for loading A12 Kernel _DocumentV2_.

[source,java,title="KernelDocumentV2Provider interface"]
----
include::../../sourceCode/engine-runtime/main/java/com/mgmtp/a12/print/engine/runtime/KernelDocumentV2Provider.java[tag=!*]
----

[#kernel_document_provider]
== KernelDocumentProvider (Deprecated)

CAUTION: Will be replaced with <<kernel_document_v2_provider, KernelDocumentV2Provider>> in 2026.06.

`KernelDocumentProvider` is an interface for loading A12 Kernel _IDocument_.

[source,java,title="KernelDocumentProvider interface"]
----
include::../../sourceCode/engine-runtime/main/java/com/mgmtp/a12/print/engine/runtime/KernelDocumentProvider.java[tag=!*]
----

[#typesetting_model_provider]
== TypesettingModelProvider

`TypesettingModelProvider` is an interface for loading Typesetting Models. They can be created within the SME (link:/docs/PRINT_ENGINE/print-modeling-documentation/index.html#TypesettingModel[Typesetting Model Configuration]).

[source,java,title="TypesettingModelProvider interface"]
----
include::../../sourceCode/engine-runtime/main/java/com/mgmtp/a12/print/engine/runtime/TypesettingModelProvider.java[tag=!*]
----

[#attachment_provider]
== AttachmentProvider

`AttachmentProvider` is an interface for loading Attachments as _ByteArrayInputStream_.

[source,java,title="AttachmentProvider interface"]
----
include::../../sourceCode/engine-runtime/main/java/com/mgmtp/a12/print/engine/runtime/AttachmentProvider.java[tag=!*]
----

[#page_range_restriction]
== PageRangeRestriction

`PageRangeRestriction` is a `JobRestriction`, which is able to restrict the resulting pages in the PDF.
The user is able to use one of the auxiliary methods or the `Builder` to create a `PageRangeRestriction`.

A starting index must be defined.
The end index can be defined and is then to be understood as exclusive.
If no end index is defined, all pages after the starting index are in the output PDF.
The indices are zero-based.

It is only possible to define one `PageRangeRestriction`

[source,java,title="PageRangeRestriction"]
----
include::../../sourceCode/engine-api/restriction/PageRangeRestriction.java[tag=!*]
----

