/*
 * SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
 *
 * Copyright (c) 2012-2026 mgm technology partners GmbH
 *
 * Dual License
 * ------------
 * This source file is part of the mgm A12 Platform and available under
 * a choice of two different licenses:
 *
 * 1. Open-Source License - EUPL v1.2
 *    You may redistribute and/or modify this file under the terms of the
 *    European Union Public License, version 1.2 - see https://eupl.eu/.
 *
 * 2. Commercial License
 *    Alternatively, you may obtain a commercial license from
 *    mgm technology partners GmbH, that permits use of this software
 *    under different terms (including support and maintenance services).
 *
 *    Please contact a12-license@mgm-tp.com for more information.
 *
 * You must select and comply with exactly one of the above license options.
 *
 * Warranty Disclaimer (applies to either option)
 * ----------------------------------------------
 * THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND,
 * WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE
 * LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
 */
/* This file is automatically generated from the migration tool utils package */
import type { MigrationStep } from "@com.mgmtp.a12.migrationtool/migrationtool-core/types";

import Schema_2_1_0 from "./version-2.1.0/schema.json" with { type: "json" };
import Schema_3_0_0 from "./version-3.0.0/schema.json" with { type: "json" };
import Schema_3_1_0 from "./version-3.1.0/schema.json" with { type: "json" };
import Schema_3_2_0 from "./version-3.2.0/schema.json" with { type: "json" };
import Schema_4_0_0 from "./version-4.0.0/schema.json" with { type: "json" };
import Transform_3_0_0rc0 from "./version-3.0.0/transform.js";
import Transform_3_0_0 from "./version-3.0.0/transform_3.0.0.js";
import Transform_3_2_0rc0 from "./version-3.2.0/transform.js";
import Transform_4_0_0rc1 from "./version-4.0.0/transform-rc.1.js";
import Transform_4_0_0rc2 from "./version-4.0.0/transform-rc.2.js";
import Transform_4_0_0rc3 from "./version-4.0.0/transform-rc.3.js";

export const MIGRATION_STEPS: MigrationStep[] = [
	{ version: "2.1.0", schema: Schema_2_1_0 },
	{ version: "2.1.1", schema: Schema_2_1_0 },
	{ version: "2.1.2", schema: Schema_2_1_0 },
	{ version: "2.1.3", schema: Schema_2_1_0 },
	{ version: "2.2.0-build.0", schema: Schema_2_1_0 },
	{ version: "2.2.0-build.1", schema: Schema_2_1_0 },
	{ version: "2.2.0-build.2", schema: Schema_2_1_0 },
	{ version: "2.2.0-build.3", schema: Schema_2_1_0 },
	{ version: "2.2.0-rc.0", schema: Schema_2_1_0 },
	{ version: "2.2.0-rc.1", schema: Schema_2_1_0 },
	{ version: "2.2.0", schema: Schema_2_1_0 },
	{ version: "2.2.1", schema: Schema_2_1_0 },
	{ version: "2.2.2", schema: Schema_2_1_0 },
	{ version: "2.2.3", schema: Schema_2_1_0 },
	{ version: "2.2.4", schema: Schema_2_1_0 },
	{ version: "2.2.5", schema: Schema_2_1_0 },
	{ version: "2.2.6", schema: Schema_2_1_0 },
	{ version: "2.2.7", schema: Schema_2_1_0 },
	{ version: "3.0.0-pre.0", schema: Schema_2_1_0 },
	{ version: "3.0.0-pre.1", schema: Schema_2_1_0 },
	{ version: "3.0.0-pre.2", schema: Schema_2_1_0 },
	{ version: "3.0.0-pre.3", schema: Schema_2_1_0 },
	{ version: "3.0.0-pre.4", schema: Schema_2_1_0 },
	{ version: "3.0.0-rc.0", schema: Schema_3_0_0, transform: Transform_3_0_0rc0 },
	{ version: "3.0.0-rc.1", schema: Schema_3_0_0 },
	{ version: "3.0.0-rc.2", schema: Schema_3_0_0 },
	{ version: "3.0.0", schema: Schema_3_0_0, transform: Transform_3_0_0 },
	{ version: "3.0.1", schema: Schema_3_0_0 },
	{ version: "3.0.2", schema: Schema_3_0_0 },
	{ version: "3.0.3", schema: Schema_3_0_0 },
	{ version: "3.1.0-rc.0", schema: Schema_3_1_0 },
	{ version: "3.1.0", schema: Schema_3_1_0 },
	{ version: "3.1.1-pre.0", schema: Schema_3_1_0 },
	{ version: "3.1.1-rc.0", schema: Schema_3_1_0 },
	{ version: "3.1.1-rc.1", schema: Schema_3_1_0 },
	{ version: "3.2.0-rc.0", schema: Schema_3_2_0, transform: Transform_3_2_0rc0 },
	{ version: "3.2.0-rc.1", schema: Schema_3_2_0 },
	{ version: "3.2.0", schema: Schema_3_2_0 },
	{ version: "4.0.0-rc.1", schema: Schema_4_0_0, transform: Transform_4_0_0rc1 },
	{ version: "4.0.0-rc.2", schema: Schema_4_0_0, transform: Transform_4_0_0rc2 },
	{ version: "4.0.0-rc.3", schema: Schema_4_0_0, transform: Transform_4_0_0rc3 },
	{ version: "4.0.0", schema: Schema_4_0_0 },
];
