////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
= print-shell [[PrintShell]]

This chapter covers the print-shell. This is a command line interface which allows to use some handy tools of the Print Engine.

== Prerequisites

print-shell is available in the artifactory.

To run the print-shell, Java 21 must be installed and available from the command line.

== Start print-shell

The print-shell must be started in the command line with the command:

[source,bash,subs="attributes"]
----
java -jar print-shell-[PrintEngineVersion].jar
----

The print-shell is a handy tool, that allows you to use the following commands:

=== Migration [[PrintShellMigration]]

Until Print Model version `2.1.0` the migration is done by the print-shell command line interface.

CAUTION: Since with release 2.1.0 we introduce a new typescript based migration tool to align with overall A12 standards. The print-shell migration will no longer validate and pretty print starting from version 3.0.0. To ensure the same output as prior versions, you need to run the print-shell migration and then the typescript migration in order to migrate to the latest version. In releases after 2.1.0, only the typescript migration will be relevant.

[source,bash,subs="attributes"]
----
migrate -w workspacePath -o overwrite
----

* `workspacePath`: Path to the workspace containing the Print Models.
* `overwrite`: `true` if you want your Print Models to be overwritten by the migrated models, `false` otherwise.

=== Comparison of Two PDF-Documents.

[source,bash,subs="attributes"]
----
compare -1 pdf1 -2 pdf2 -p percent
----

* `pdf1`: Name of the first PDF-document
* `pdf2`: Name of the second PDF-document
* `percent`: The percent of the allowing pixels to be different for comparison. Valid values range from 0 to 100. The default value is 0

=== Comparison of All PDF-Documents With the Same Name.

[source,bash,subs="attributes"]
----
compare-all -w workspacePath -p percent --equal equal
----

* `workspacePath`: Path to the workspace containing the PDF-documents.
* `percent`: The percent of the allowing pixels to be different for comparison. Valid values range from 0 to 100. The default value is 0
* `equal`: This defines how the matched PDF files are found. By default the command is checking for `startWith`. If this parameter is set to true the file name of the PDF files need to be completely equal.

[#print_shell_printing]
=== Printing a Specific Print Model.

[source,bash,subs="attributes"]
----
print -w workspacePath -p printModelId -d documentId -t timeZone --locale localeString --useExperimentalRendering useExperimentalRendering --suffix suffix
----

* `workspacePath`: Path to the workspace containing the Print Models.
* `printModelId`: ID of the Print Model used for the print operation.
* `documentId`: ID of the A12 Document used for the print operation.
Example: For document file `DomainDocument-1` the ID is `1`.
* `timeZone`: Timezone for the print operation.
Example: `GMT`
* `localeString`: Locale to use for the print operation.
Example: `de`
* `useExperimentalRendering`: This flag controls, which rendering pipeline is used. It is set to false by default, which means that <<legacy_rendering_mode, Legacy Rendering Mode>> will be used. For the default rendering mode, set it to be true. With the deprecation of the Legacy Rendering Mode in the 2026.06 release, this flag will be removed.
* `suffix`: The suffix is attached separated with a '-' on the final PDF file name


=== Printing All Print Models in the Current Workspace.

[source,bash,subs="attributes"]
----
print-all -w workspacePath -t timeZone --locale localeString --useExperimentalRendering useExperimentalRendering --suffix suffix --filter filter
----

* `workspacePath`: Path to the workspace containing the Print Models.
* `timeZone`: Timezone for the print operation.
Example: `GMT`
* `localeString`: Locale to use for the print operation.
Example: `de`
* `useExperimentalRendering`: This flag controls, which rendering pipeline is used. It is set to false by default, which means that <<legacy_rendering_mode, Legacy Rendering Mode>> will be used. For the default rendering mode, set it to be true. With the deprecation of the Legacy Rendering Mode in the 2026.06 release, this flag will be removed.
* `suffix`: The suffix is attached separated with a '-' on the final PDF file name
* `filter`: With the filter option it is possible to define a Regex to print only Print Models with IDs that match. If empty, all Print models in the workspace are printed.
