////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
= Dependency

This section covers the dependencies necessary for integrating the Print Engine into a Maven or Gradle application.

For the usage with Maven, the following dependencies need to be added in the applications POM-file:

Maven plugin::

[source,bash]
----
<dependency>
    <groupId>com.mgmtp.a12.print</groupId>
    <artifactId>print-engine-api</artifactId>
    <version>{printEngineVersion}</version>
</dependency>

<dependency>
    <groupId>com.mgmtp.a12.print</groupId>
    <artifactId>print-engine-runtime</artifactId>
    <version>{printEngineVersion}</version>
</dependency>
----

For the usage with Gradle, the following dependencies need to be added in the applications `build.gradle` file:

Gradle plugin::

[source,bash]
----
...
dependencies {
	...
	implementation("com.mgmtp.a12.print:print-engine-api:${printEngineVersion}")
	implementation("com.mgmtp.a12.print:print-engine-runtime:${printEngineVersion}")
	...
}
----
