////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
[#configuration]
= Configuration

This section covers the core configurations of the Print Engine, necessary for printing valid PDF-documents.

You can either create these configurations directly or if you are using Spring you can do so by using the `@Bean` annotation in the Configuration class.

== Direct Configuration

=== Creating the PrintJobManagerApi

First of all, we need to define the PrintJobManagerApi.

NOTE: the PrintJobManagerApi may be called by any thread from the ExecutorService.
These threads will not carry a `SecurityContext`.

[source,java]
----
include::../../sourceCode/print-shell/main/java/com/mgmtp/a12/print/shell/internal/ApplicationShell.java[tag=PrintJobManagerApi,indent=0]
----
<1> This should be changed by your local service accordingly.
<2> This should be changed by your local service accordingly.

=== Creating the ExecutorService

The <<print_engine_runtime, Print Engine Runtime>> provides a default implementation for the ExecutorService:
[source,java]

----
ExecutorServiceFactory.getInstance(Runtime.getRuntime().availableProcessors(), "print-pool");
----

Alternatively, you can declare your own ExecutorService:

[source,java]
----
include::../../sourceCode/engine-runtime-test/com/mgmtp/a12/print/engine/runtime/test/internal/PrintTestUtil.java[tag=ExecutorService,indent=0]
----

[#print_job_manager_usage]
=== Creating PrintJobManager and PrintEngine

Then we can create PrintJobManager with <<static_image_provider, StaticImageProvider>> and <<pdf_box_print_engine_runtime, PdfBoxPrintEngine>>.

[source,java]
----
include::../../sourceCode/print-shell/main/java/com/mgmtp/a12/print/shell/internal/service/PrintService.java[tag=PrintJobManager,indent=0]
include::../../sourceCode/print-shell/main/java/com/mgmtp/a12/print/shell/internal/commands/PrintCommand.java[tag=PdfPrintEngine,indent=0]
----

The possibilities of the configs are described in <<pdf_box_print_engine_config, PdfBoxPrintEngineConfig>>.

== Using the `@Bean` Annotation

Example::

[source,java,title="Configuration class"]
----
public class PrintConfiguration {
	public static final String PRINT_THREAD_POOL = "printThreadPool";

	@Bean
	@Qualifier(PRINT_THREAD_POOL)
	public ExecutorService printThreadPool() {
		return ExecutorServiceFactory.getInstance();
	}

	@Bean
	public PrintJobManager.PrintJobManagerApi printJobManagerApi() {
		return new PrintJobManager.PrintJobManagerApi() {
			@Override
			public String loadPrintModel(String id) {
				// load print model content with the provided id <1>
			}

			@Override
			public IDocumentModel loadDocumentModel(String id) {
				// load document model with the provided id <2>
			}
		};
	}

	@Bean
	public PdfBoxPrintEngine pdfPrintEngine(@lombok.NonNull @Qualifier(PRINT_THREAD_POOL) ExecutorService printThreadPool) {
		return new com.mgmtp.a12.print.engine.runtime.pdfBox.PdfBoxPrintEngine(
			printThreadPool,
			PdfBoxPrintEngineConfig.DEFAULT.toBuilder()
				.availableFonts(PrintEngineConfig.DEFAULT_FONTS) // <3>
				.build()
		);
	}
}
----

<1> Load Print Model content.
The implementation should be changed by your local service accordingly.
<2> Load IDocumentModel.
The implementation should be changed by your local service accordingly.
<3> Customization fonts could be set for the PdfBoxPrintEngineConfig.
