////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
= Print Model Editor Light

This chapter describes the integration of the `PrintModelEditorLight` component into a React Frontend application.
It allows the creation of client applications where users can edit PrintModels.

CAUTION: The PrintModelEditorLight is an **experimental** simplified version of the **Print Model Editor**, which itself is part of the standalone **Simple Model Editor** (SME) application.
For most use cases, we strongly recommend using the SME as the standard tool for managing PrintModels. Integration of the PrintModelEditorLight into your own frontend application is generally not advised.

If you want to integrate this component or if your project has other requirements, feel free to contact the A12 Print Engine team (link:https://discourse.geta12.com/c/engines-specific/print-engine[Discourse])

:leveloffset: +1

include::0501_dependency.adoc[]

include::0502_usage.adoc[]

:leveloffset: -1

