////
SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-commercial
Copyright (c) 2012-2026 mgm technology partners GmbH
Dual License
This source file is part of the mgm A12 Platform and available under a choice of two different licenses:
1. Open-Source License - EUPL v1.2
You may redistribute and/or modify this file under the terms of the European Union Public License, version 1.2 - see https://eupl.eu/.
2. Commercial License
Alternatively, you may obtain a commercial license from mgm technology partners GmbH, that permits use of this software under different terms (including support and maintenance services).

Please contact a12-license@mgm-tp.com for more information.

You must select and comply with exactly one of the above license options.

Warranty Disclaimer (applies to either option)
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, EXCEPT WHERE SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID. SEE THE RESPECTIVE LICENSE TEXT FOR DETAILS.
////
= Breaking Change Management

Here, we define the A12 Print Engine public API and define which changes to this API we consider breaking and non-breaking.

== Definition of Version

The Print Engine component defines a single version. All artifacts (Java and Javascript) that belong to the Print Engine share the same version.

== Definition / distinction of different APIs

[cols="1,1",options="header"]
|===
| Public API | internal

| - All sources that are not `internal`.

  - Everything that is mentioned in the documentation.

| - All sources in folders named `internal` or sub-folders thereof, or for Java sources in packages named `internal` or sub-packages thereof.

  - Also all sources in modules whose `artifactId` contains `internal`.
|===

Code changes which do not affect the Public API type surface and change broken features (i.e. features that did not work like expected) which are fixed are not regarded as Breaking Changes.

== Breaking Changes

[cols="1,1,1",options="header"]
|===
| Area | Breaking | Non-breaking

| PDF
| - Layout changes in the output PDF.

  - Changes that require manual user migration.

| - Adding new features / new components.

  - Fully automated migration that does not result in layout changes.

| libraries

| - Adding new base interfaces.

  - Changing function signature.

| - Adding a new interface.

  - Adding an optional function definition / signature.
|===
